kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      networking:
        dnsDomain: "eidolons.cloud"
  - role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none